import type { TeamemTools } from './tools/index.js';

export const TOOL_NAMES = [
  'teamem.get_updates',
  'teamem.claim_scope',
  'teamem.release_scope',
  'teamem.release_scope_via_git',
  'teamem.publish_decision',
  'teamem.amend_decision',
  'teamem.supersede_decision',
  'teamem.record_decision',
  'teamem.get_contract_state',
  'teamem.get_briefing',
  'teamem.export_space_rules_snapshot',
  'teamem.session_sync',
  'teamem.update_space_rules',
  'teamem.whoami',
  'teamem.post_message',
  'teamem.read_thread',
  'teamem.update_coord_pref',
  'teamem.share_finding',
  'teamem.get_finding',
  'teamem.acknowledge_finding',
  'teamem.share_artifact',
  'teamem.queue_pending_edit',
  'teamem.clear_queue',
  'teamem.request_edit_permission',
  'teamem.respond_permission_request',
  'teamem.agent_focus_changed',
  'teamem.open_dispute',
  'teamem.dispute_post_move',
  'teamem.end_dispute',
  'teamem.update_dispute_terminations',
  'teamem.space_leave',
  'teamem.space_kick',
  'teamem.space_rotate_code',
  'teamem.force_release',
  'teamem.fetch_unread_notifications',
  'teamem.pause_claims_for_branch',
  'teamem.resume_claims_for_branch',
  'teamem.list_claims'
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];

export function createToolRegistry(
  tools: TeamemTools
): Record<ToolName, unknown> {
  return {
    'teamem.get_updates': tools.getUpdates,
    'teamem.claim_scope': tools.claimScope,
    'teamem.release_scope': tools.releaseScope,
    'teamem.release_scope_via_git': tools.releaseScopeViaGit,
    'teamem.publish_decision': tools.publishDecision,
    'teamem.amend_decision': tools.amendDecision,
    'teamem.supersede_decision': tools.supersedeDecision,
    'teamem.record_decision': tools.recordDecision,
    'teamem.get_contract_state': tools.getContractState,
    'teamem.get_briefing': tools.getBriefing,
    'teamem.export_space_rules_snapshot': tools.exportSpaceRulesSnapshot,
    'teamem.session_sync': tools.sessionSync,
    'teamem.update_space_rules': tools.updateSpaceRules,
    'teamem.whoami': tools.whoami,
    'teamem.post_message': tools.postMessage,
    'teamem.read_thread': tools.readThread,
    'teamem.update_coord_pref': tools.updateCoordPref,
    'teamem.share_finding': tools.shareFinding,
    'teamem.get_finding': tools.getFinding,
    'teamem.acknowledge_finding': tools.acknowledgeFinding,
    'teamem.share_artifact': tools.shareArtifact,
    'teamem.queue_pending_edit': tools.queuePendingEdit,
    'teamem.clear_queue': tools.clearQueue,
    'teamem.request_edit_permission': tools.requestEditPermission,
    'teamem.respond_permission_request': tools.respondPermissionRequest,
    'teamem.agent_focus_changed': tools.agentFocusChanged,
    'teamem.open_dispute': tools.openDispute,
    'teamem.dispute_post_move': tools.disputePostMove,
    'teamem.end_dispute': tools.endDispute,
    'teamem.update_dispute_terminations': tools.updateDisputeTerminations,
    'teamem.space_leave': tools.spaceLeave,
    'teamem.space_kick': tools.spaceKick,
    'teamem.space_rotate_code': tools.spaceRotateCode,
    'teamem.force_release': tools.forceRelease,
    'teamem.fetch_unread_notifications': tools.fetchUnreadNotifications,
    'teamem.pause_claims_for_branch': tools.pauseClaimsForBranch,
    'teamem.resume_claims_for_branch': tools.resumeClaimsForBranch,
    'teamem.list_claims': tools.listClaims
  };
}
